# Generated by Django 6.0.3 on 2026-03-16 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_category_remove_productimage_product_and_more'),
        ('orders', '0002_remove_orderitem_product_remove_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
