# Generated by Django 6.0.3 on 2026-04-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_gameimage_alt_text_gameimage_is_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
