# Generated by Django 6.0.3 on 2026-04-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_game_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='stock',
        ),
    ]
